export const CONFIG_TRANSFER_PASSPHRASE_MIN_LENGTH = 12;
export const CONFIG_TRANSFER_PASSPHRASE_MAX_LENGTH = 256;
export const CONFIG_TRANSFER_MAX_PAYLOAD_BYTES = 6 * 1024 * 1024;
export const CONFIG_TRANSFER_MAX_FILE_BYTES = 10 * 1024 * 1024;
