/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authDownloadRecoveryKeyRouteImport } from './routes/(auth)/download-recovery-key'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DesktopTrayRouteImport } from './routes/desktop/tray'
import { Route as authLoginErrorRouteImport } from './routes/(auth)/login.error'
import { Route as dashboardActivityIndexRouteImport } from './routes/(dashboard)/activity/index'
import { Route as dashboardAdminIndexRouteImport } from './routes/(dashboard)/admin/index'
import { Route as dashboardBackupsIndexRouteImport } from './routes/(dashboard)/backups/index'
import { Route as dashboardBackupsCreateRouteImport } from './routes/(dashboard)/backups/create'
import { Route as dashboardNotificationsIndexRouteImport } from './routes/(dashboard)/notifications/index'
import { Route as dashboardNotificationsCreateRouteImport } from './routes/(dashboard)/notifications/create'
import { Route as dashboardRepositoriesIndexRouteImport } from './routes/(dashboard)/repositories/index'
import { Route as dashboardRepositoriesCreateRouteImport } from './routes/(dashboard)/repositories/create'
import { Route as dashboardSettingsIndexRouteImport } from './routes/(dashboard)/settings/index'
import { Route as dashboardVolumesIndexRouteImport } from './routes/(dashboard)/volumes/index'
import { Route as dashboardVolumesCreateRouteImport } from './routes/(dashboard)/volumes/create'
import { Route as dashboardBackupsBackupIdIndexRouteImport } from './routes/(dashboard)/backups/$backupId/index'
import { Route as dashboardBackupsBackupIdEditRouteImport } from './routes/(dashboard)/backups/$backupId/edit'
import { Route as dashboardNotificationsNotificationIdIndexRouteImport } from './routes/(dashboard)/notifications/$notificationId/index'
import { Route as dashboardNotificationsNotificationIdEditRouteImport } from './routes/(dashboard)/notifications/$notificationId/edit'
import { Route as dashboardRepositoriesRepositoryIdIndexRouteImport } from './routes/(dashboard)/repositories/$repositoryId/index'
import { Route as dashboardRepositoriesRepositoryIdEditRouteImport } from './routes/(dashboard)/repositories/$repositoryId/edit'
import { Route as dashboardSettingsSsoNewRouteImport } from './routes/(dashboard)/settings/sso/new'
import { Route as dashboardVolumesVolumeIdIndexRouteImport } from './routes/(dashboard)/volumes/$volumeId/index'
import { Route as dashboardVolumesVolumeIdEditRouteImport } from './routes/(dashboard)/volumes/$volumeId/edit'
import { Route as dashboardBackupsBackupIdSnapshotIdRestoreRouteImport } from './routes/(dashboard)/backups/$backupId/$snapshotId.restore'
import { Route as dashboardRepositoriesRepositoryIdSnapshotIdIndexRouteImport } from './routes/(dashboard)/repositories/$repositoryId/$snapshotId/index'
import { Route as dashboardRepositoriesRepositoryIdSnapshotIdRestoreRouteImport } from './routes/(dashboard)/repositories/$repositoryId/$snapshotId/restore'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authDownloadRecoveryKeyRoute = authDownloadRecoveryKeyRouteImport.update({
  id: '/download-recovery-key',
  path: '/download-recovery-key',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopTrayRoute = DesktopTrayRouteImport.update({
  id: '/desktop/tray',
  path: '/desktop/tray',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginErrorRoute = authLoginErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => authLoginRoute,
} as any)
const dashboardActivityIndexRoute = dashboardActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardAdminIndexRoute = dashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardBackupsIndexRoute = dashboardBackupsIndexRouteImport.update({
  id: '/backups/',
  path: '/backups/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardBackupsCreateRoute = dashboardBackupsCreateRouteImport.update({
  id: '/backups/create',
  path: '/backups/create',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardNotificationsIndexRoute =
  dashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardNotificationsCreateRoute =
  dashboardNotificationsCreateRouteImport.update({
    id: '/notifications/create',
    path: '/notifications/create',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesIndexRoute =
  dashboardRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesCreateRoute =
  dashboardRepositoriesCreateRouteImport.update({
    id: '/repositories/create',
    path: '/repositories/create',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSettingsIndexRoute = dashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardVolumesIndexRoute = dashboardVolumesIndexRouteImport.update({
  id: '/volumes/',
  path: '/volumes/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardVolumesCreateRoute = dashboardVolumesCreateRouteImport.update({
  id: '/volumes/create',
  path: '/volumes/create',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardBackupsBackupIdIndexRoute =
  dashboardBackupsBackupIdIndexRouteImport.update({
    id: '/backups/$backupId/',
    path: '/backups/$backupId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardBackupsBackupIdEditRoute =
  dashboardBackupsBackupIdEditRouteImport.update({
    id: '/backups/$backupId/edit',
    path: '/backups/$backupId/edit',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardNotificationsNotificationIdIndexRoute =
  dashboardNotificationsNotificationIdIndexRouteImport.update({
    id: '/notifications/$notificationId/',
    path: '/notifications/$notificationId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardNotificationsNotificationIdEditRoute =
  dashboardNotificationsNotificationIdEditRouteImport.update({
    id: '/notifications/$notificationId/edit',
    path: '/notifications/$notificationId/edit',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesRepositoryIdIndexRoute =
  dashboardRepositoriesRepositoryIdIndexRouteImport.update({
    id: '/repositories/$repositoryId/',
    path: '/repositories/$repositoryId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesRepositoryIdEditRoute =
  dashboardRepositoriesRepositoryIdEditRouteImport.update({
    id: '/repositories/$repositoryId/edit',
    path: '/repositories/$repositoryId/edit',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSettingsSsoNewRoute = dashboardSettingsSsoNewRouteImport.update({
  id: '/settings/sso/new',
  path: '/settings/sso/new',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardVolumesVolumeIdIndexRoute =
  dashboardVolumesVolumeIdIndexRouteImport.update({
    id: '/volumes/$volumeId/',
    path: '/volumes/$volumeId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardVolumesVolumeIdEditRoute =
  dashboardVolumesVolumeIdEditRouteImport.update({
    id: '/volumes/$volumeId/edit',
    path: '/volumes/$volumeId/edit',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardBackupsBackupIdSnapshotIdRestoreRoute =
  dashboardBackupsBackupIdSnapshotIdRestoreRouteImport.update({
    id: '/backups/$backupId/$snapshotId/restore',
    path: '/backups/$backupId/$snapshotId/restore',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute =
  dashboardRepositoriesRepositoryIdSnapshotIdIndexRouteImport.update({
    id: '/repositories/$repositoryId/$snapshotId/',
    path: '/repositories/$repositoryId/$snapshotId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute =
  dashboardRepositoriesRepositoryIdSnapshotIdRestoreRouteImport.update({
    id: '/repositories/$repositoryId/$snapshotId/restore',
    path: '/repositories/$repositoryId/$snapshotId/restore',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download-recovery-key': typeof authDownloadRecoveryKeyRoute
  '/login': typeof authLoginRouteWithChildren
  '/onboarding': typeof authOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/desktop/tray': typeof DesktopTrayRoute
  '/login/error': typeof authLoginErrorRoute
  '/backups/create': typeof dashboardBackupsCreateRoute
  '/notifications/create': typeof dashboardNotificationsCreateRoute
  '/repositories/create': typeof dashboardRepositoriesCreateRoute
  '/volumes/create': typeof dashboardVolumesCreateRoute
  '/activity/': typeof dashboardActivityIndexRoute
  '/admin/': typeof dashboardAdminIndexRoute
  '/backups/': typeof dashboardBackupsIndexRoute
  '/notifications/': typeof dashboardNotificationsIndexRoute
  '/repositories/': typeof dashboardRepositoriesIndexRoute
  '/settings/': typeof dashboardSettingsIndexRoute
  '/volumes/': typeof dashboardVolumesIndexRoute
  '/backups/$backupId/edit': typeof dashboardBackupsBackupIdEditRoute
  '/notifications/$notificationId/edit': typeof dashboardNotificationsNotificationIdEditRoute
  '/repositories/$repositoryId/edit': typeof dashboardRepositoriesRepositoryIdEditRoute
  '/settings/sso/new': typeof dashboardSettingsSsoNewRoute
  '/volumes/$volumeId/edit': typeof dashboardVolumesVolumeIdEditRoute
  '/backups/$backupId/': typeof dashboardBackupsBackupIdIndexRoute
  '/notifications/$notificationId/': typeof dashboardNotificationsNotificationIdIndexRoute
  '/repositories/$repositoryId/': typeof dashboardRepositoriesRepositoryIdIndexRoute
  '/volumes/$volumeId/': typeof dashboardVolumesVolumeIdIndexRoute
  '/backups/$backupId/$snapshotId/restore': typeof dashboardBackupsBackupIdSnapshotIdRestoreRoute
  '/repositories/$repositoryId/$snapshotId/restore': typeof dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute
  '/repositories/$repositoryId/$snapshotId/': typeof dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download-recovery-key': typeof authDownloadRecoveryKeyRoute
  '/login': typeof authLoginRouteWithChildren
  '/onboarding': typeof authOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/desktop/tray': typeof DesktopTrayRoute
  '/login/error': typeof authLoginErrorRoute
  '/backups/create': typeof dashboardBackupsCreateRoute
  '/notifications/create': typeof dashboardNotificationsCreateRoute
  '/repositories/create': typeof dashboardRepositoriesCreateRoute
  '/volumes/create': typeof dashboardVolumesCreateRoute
  '/activity': typeof dashboardActivityIndexRoute
  '/admin': typeof dashboardAdminIndexRoute
  '/backups': typeof dashboardBackupsIndexRoute
  '/notifications': typeof dashboardNotificationsIndexRoute
  '/repositories': typeof dashboardRepositoriesIndexRoute
  '/settings': typeof dashboardSettingsIndexRoute
  '/volumes': typeof dashboardVolumesIndexRoute
  '/backups/$backupId/edit': typeof dashboardBackupsBackupIdEditRoute
  '/notifications/$notificationId/edit': typeof dashboardNotificationsNotificationIdEditRoute
  '/repositories/$repositoryId/edit': typeof dashboardRepositoriesRepositoryIdEditRoute
  '/settings/sso/new': typeof dashboardSettingsSsoNewRoute
  '/volumes/$volumeId/edit': typeof dashboardVolumesVolumeIdEditRoute
  '/backups/$backupId': typeof dashboardBackupsBackupIdIndexRoute
  '/notifications/$notificationId': typeof dashboardNotificationsNotificationIdIndexRoute
  '/repositories/$repositoryId': typeof dashboardRepositoriesRepositoryIdIndexRoute
  '/volumes/$volumeId': typeof dashboardVolumesVolumeIdIndexRoute
  '/backups/$backupId/$snapshotId/restore': typeof dashboardBackupsBackupIdSnapshotIdRestoreRoute
  '/repositories/$repositoryId/$snapshotId/restore': typeof dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute
  '/repositories/$repositoryId/$snapshotId': typeof dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/download-recovery-key': typeof authDownloadRecoveryKeyRoute
  '/(auth)/login': typeof authLoginRouteWithChildren
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/desktop/tray': typeof DesktopTrayRoute
  '/(auth)/login/error': typeof authLoginErrorRoute
  '/(dashboard)/backups/create': typeof dashboardBackupsCreateRoute
  '/(dashboard)/notifications/create': typeof dashboardNotificationsCreateRoute
  '/(dashboard)/repositories/create': typeof dashboardRepositoriesCreateRoute
  '/(dashboard)/volumes/create': typeof dashboardVolumesCreateRoute
  '/(dashboard)/activity/': typeof dashboardActivityIndexRoute
  '/(dashboard)/admin/': typeof dashboardAdminIndexRoute
  '/(dashboard)/backups/': typeof dashboardBackupsIndexRoute
  '/(dashboard)/notifications/': typeof dashboardNotificationsIndexRoute
  '/(dashboard)/repositories/': typeof dashboardRepositoriesIndexRoute
  '/(dashboard)/settings/': typeof dashboardSettingsIndexRoute
  '/(dashboard)/volumes/': typeof dashboardVolumesIndexRoute
  '/(dashboard)/backups/$backupId/edit': typeof dashboardBackupsBackupIdEditRoute
  '/(dashboard)/notifications/$notificationId/edit': typeof dashboardNotificationsNotificationIdEditRoute
  '/(dashboard)/repositories/$repositoryId/edit': typeof dashboardRepositoriesRepositoryIdEditRoute
  '/(dashboard)/settings/sso/new': typeof dashboardSettingsSsoNewRoute
  '/(dashboard)/volumes/$volumeId/edit': typeof dashboardVolumesVolumeIdEditRoute
  '/(dashboard)/backups/$backupId/': typeof dashboardBackupsBackupIdIndexRoute
  '/(dashboard)/notifications/$notificationId/': typeof dashboardNotificationsNotificationIdIndexRoute
  '/(dashboard)/repositories/$repositoryId/': typeof dashboardRepositoriesRepositoryIdIndexRoute
  '/(dashboard)/volumes/$volumeId/': typeof dashboardVolumesVolumeIdIndexRoute
  '/(dashboard)/backups/$backupId/$snapshotId/restore': typeof dashboardBackupsBackupIdSnapshotIdRestoreRoute
  '/(dashboard)/repositories/$repositoryId/$snapshotId/restore': typeof dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute
  '/(dashboard)/repositories/$repositoryId/$snapshotId/': typeof dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download-recovery-key'
    | '/login'
    | '/onboarding'
    | '/api/$'
    | '/desktop/tray'
    | '/login/error'
    | '/backups/create'
    | '/notifications/create'
    | '/repositories/create'
    | '/volumes/create'
    | '/activity/'
    | '/admin/'
    | '/backups/'
    | '/notifications/'
    | '/repositories/'
    | '/settings/'
    | '/volumes/'
    | '/backups/$backupId/edit'
    | '/notifications/$notificationId/edit'
    | '/repositories/$repositoryId/edit'
    | '/settings/sso/new'
    | '/volumes/$volumeId/edit'
    | '/backups/$backupId/'
    | '/notifications/$notificationId/'
    | '/repositories/$repositoryId/'
    | '/volumes/$volumeId/'
    | '/backups/$backupId/$snapshotId/restore'
    | '/repositories/$repositoryId/$snapshotId/restore'
    | '/repositories/$repositoryId/$snapshotId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download-recovery-key'
    | '/login'
    | '/onboarding'
    | '/api/$'
    | '/desktop/tray'
    | '/login/error'
    | '/backups/create'
    | '/notifications/create'
    | '/repositories/create'
    | '/volumes/create'
    | '/activity'
    | '/admin'
    | '/backups'
    | '/notifications'
    | '/repositories'
    | '/settings'
    | '/volumes'
    | '/backups/$backupId/edit'
    | '/notifications/$notificationId/edit'
    | '/repositories/$repositoryId/edit'
    | '/settings/sso/new'
    | '/volumes/$volumeId/edit'
    | '/backups/$backupId'
    | '/notifications/$notificationId'
    | '/repositories/$repositoryId'
    | '/volumes/$volumeId'
    | '/backups/$backupId/$snapshotId/restore'
    | '/repositories/$repositoryId/$snapshotId/restore'
    | '/repositories/$repositoryId/$snapshotId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(dashboard)'
    | '/(auth)/download-recovery-key'
    | '/(auth)/login'
    | '/(auth)/onboarding'
    | '/api/$'
    | '/desktop/tray'
    | '/(auth)/login/error'
    | '/(dashboard)/backups/create'
    | '/(dashboard)/notifications/create'
    | '/(dashboard)/repositories/create'
    | '/(dashboard)/volumes/create'
    | '/(dashboard)/activity/'
    | '/(dashboard)/admin/'
    | '/(dashboard)/backups/'
    | '/(dashboard)/notifications/'
    | '/(dashboard)/repositories/'
    | '/(dashboard)/settings/'
    | '/(dashboard)/volumes/'
    | '/(dashboard)/backups/$backupId/edit'
    | '/(dashboard)/notifications/$notificationId/edit'
    | '/(dashboard)/repositories/$repositoryId/edit'
    | '/(dashboard)/settings/sso/new'
    | '/(dashboard)/volumes/$volumeId/edit'
    | '/(dashboard)/backups/$backupId/'
    | '/(dashboard)/notifications/$notificationId/'
    | '/(dashboard)/repositories/$repositoryId/'
    | '/(dashboard)/volumes/$volumeId/'
    | '/(dashboard)/backups/$backupId/$snapshotId/restore'
    | '/(dashboard)/repositories/$repositoryId/$snapshotId/restore'
    | '/(dashboard)/repositories/$repositoryId/$snapshotId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  DesktopTrayRoute: typeof DesktopTrayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/download-recovery-key': {
      id: '/(auth)/download-recovery-key'
      path: '/download-recovery-key'
      fullPath: '/download-recovery-key'
      preLoaderRoute: typeof authDownloadRecoveryKeyRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/tray': {
      id: '/desktop/tray'
      path: '/desktop/tray'
      fullPath: '/desktop/tray'
      preLoaderRoute: typeof DesktopTrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/error': {
      id: '/(auth)/login/error'
      path: '/error'
      fullPath: '/login/error'
      preLoaderRoute: typeof authLoginErrorRouteImport
      parentRoute: typeof authLoginRoute
    }
    '/(dashboard)/activity/': {
      id: '/(dashboard)/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof dashboardActivityIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/admin/': {
      id: '/(dashboard)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof dashboardAdminIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/': {
      id: '/(dashboard)/backups/'
      path: '/backups'
      fullPath: '/backups/'
      preLoaderRoute: typeof dashboardBackupsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/create': {
      id: '/(dashboard)/backups/create'
      path: '/backups/create'
      fullPath: '/backups/create'
      preLoaderRoute: typeof dashboardBackupsCreateRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/notifications/': {
      id: '/(dashboard)/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof dashboardNotificationsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/notifications/create': {
      id: '/(dashboard)/notifications/create'
      path: '/notifications/create'
      fullPath: '/notifications/create'
      preLoaderRoute: typeof dashboardNotificationsCreateRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/': {
      id: '/(dashboard)/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof dashboardRepositoriesIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/create': {
      id: '/(dashboard)/repositories/create'
      path: '/repositories/create'
      fullPath: '/repositories/create'
      preLoaderRoute: typeof dashboardRepositoriesCreateRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/settings/': {
      id: '/(dashboard)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof dashboardSettingsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/volumes/': {
      id: '/(dashboard)/volumes/'
      path: '/volumes'
      fullPath: '/volumes/'
      preLoaderRoute: typeof dashboardVolumesIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/volumes/create': {
      id: '/(dashboard)/volumes/create'
      path: '/volumes/create'
      fullPath: '/volumes/create'
      preLoaderRoute: typeof dashboardVolumesCreateRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/$backupId/': {
      id: '/(dashboard)/backups/$backupId/'
      path: '/backups/$backupId'
      fullPath: '/backups/$backupId/'
      preLoaderRoute: typeof dashboardBackupsBackupIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/$backupId/edit': {
      id: '/(dashboard)/backups/$backupId/edit'
      path: '/backups/$backupId/edit'
      fullPath: '/backups/$backupId/edit'
      preLoaderRoute: typeof dashboardBackupsBackupIdEditRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/notifications/$notificationId/': {
      id: '/(dashboard)/notifications/$notificationId/'
      path: '/notifications/$notificationId'
      fullPath: '/notifications/$notificationId/'
      preLoaderRoute: typeof dashboardNotificationsNotificationIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/notifications/$notificationId/edit': {
      id: '/(dashboard)/notifications/$notificationId/edit'
      path: '/notifications/$notificationId/edit'
      fullPath: '/notifications/$notificationId/edit'
      preLoaderRoute: typeof dashboardNotificationsNotificationIdEditRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/$repositoryId/': {
      id: '/(dashboard)/repositories/$repositoryId/'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId/'
      preLoaderRoute: typeof dashboardRepositoriesRepositoryIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/$repositoryId/edit': {
      id: '/(dashboard)/repositories/$repositoryId/edit'
      path: '/repositories/$repositoryId/edit'
      fullPath: '/repositories/$repositoryId/edit'
      preLoaderRoute: typeof dashboardRepositoriesRepositoryIdEditRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/settings/sso/new': {
      id: '/(dashboard)/settings/sso/new'
      path: '/settings/sso/new'
      fullPath: '/settings/sso/new'
      preLoaderRoute: typeof dashboardSettingsSsoNewRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/volumes/$volumeId/': {
      id: '/(dashboard)/volumes/$volumeId/'
      path: '/volumes/$volumeId'
      fullPath: '/volumes/$volumeId/'
      preLoaderRoute: typeof dashboardVolumesVolumeIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/volumes/$volumeId/edit': {
      id: '/(dashboard)/volumes/$volumeId/edit'
      path: '/volumes/$volumeId/edit'
      fullPath: '/volumes/$volumeId/edit'
      preLoaderRoute: typeof dashboardVolumesVolumeIdEditRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/$backupId/$snapshotId/restore': {
      id: '/(dashboard)/backups/$backupId/$snapshotId/restore'
      path: '/backups/$backupId/$snapshotId/restore'
      fullPath: '/backups/$backupId/$snapshotId/restore'
      preLoaderRoute: typeof dashboardBackupsBackupIdSnapshotIdRestoreRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/$repositoryId/$snapshotId/': {
      id: '/(dashboard)/repositories/$repositoryId/$snapshotId/'
      path: '/repositories/$repositoryId/$snapshotId'
      fullPath: '/repositories/$repositoryId/$snapshotId/'
      preLoaderRoute: typeof dashboardRepositoriesRepositoryIdSnapshotIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/$repositoryId/$snapshotId/restore': {
      id: '/(dashboard)/repositories/$repositoryId/$snapshotId/restore'
      path: '/repositories/$repositoryId/$snapshotId/restore'
      fullPath: '/repositories/$repositoryId/$snapshotId/restore'
      preLoaderRoute: typeof dashboardRepositoriesRepositoryIdSnapshotIdRestoreRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface authLoginRouteChildren {
  authLoginErrorRoute: typeof authLoginErrorRoute
}

const authLoginRouteChildren: authLoginRouteChildren = {
  authLoginErrorRoute: authLoginErrorRoute,
}

const authLoginRouteWithChildren = authLoginRoute._addFileChildren(
  authLoginRouteChildren,
)

interface authRouteRouteChildren {
  authDownloadRecoveryKeyRoute: typeof authDownloadRecoveryKeyRoute
  authLoginRoute: typeof authLoginRouteWithChildren
  authOnboardingRoute: typeof authOnboardingRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authDownloadRecoveryKeyRoute: authDownloadRecoveryKeyRoute,
  authLoginRoute: authLoginRouteWithChildren,
  authOnboardingRoute: authOnboardingRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardBackupsCreateRoute: typeof dashboardBackupsCreateRoute
  dashboardNotificationsCreateRoute: typeof dashboardNotificationsCreateRoute
  dashboardRepositoriesCreateRoute: typeof dashboardRepositoriesCreateRoute
  dashboardVolumesCreateRoute: typeof dashboardVolumesCreateRoute
  dashboardActivityIndexRoute: typeof dashboardActivityIndexRoute
  dashboardAdminIndexRoute: typeof dashboardAdminIndexRoute
  dashboardBackupsIndexRoute: typeof dashboardBackupsIndexRoute
  dashboardNotificationsIndexRoute: typeof dashboardNotificationsIndexRoute
  dashboardRepositoriesIndexRoute: typeof dashboardRepositoriesIndexRoute
  dashboardSettingsIndexRoute: typeof dashboardSettingsIndexRoute
  dashboardVolumesIndexRoute: typeof dashboardVolumesIndexRoute
  dashboardBackupsBackupIdEditRoute: typeof dashboardBackupsBackupIdEditRoute
  dashboardNotificationsNotificationIdEditRoute: typeof dashboardNotificationsNotificationIdEditRoute
  dashboardRepositoriesRepositoryIdEditRoute: typeof dashboardRepositoriesRepositoryIdEditRoute
  dashboardSettingsSsoNewRoute: typeof dashboardSettingsSsoNewRoute
  dashboardVolumesVolumeIdEditRoute: typeof dashboardVolumesVolumeIdEditRoute
  dashboardBackupsBackupIdIndexRoute: typeof dashboardBackupsBackupIdIndexRoute
  dashboardNotificationsNotificationIdIndexRoute: typeof dashboardNotificationsNotificationIdIndexRoute
  dashboardRepositoriesRepositoryIdIndexRoute: typeof dashboardRepositoriesRepositoryIdIndexRoute
  dashboardVolumesVolumeIdIndexRoute: typeof dashboardVolumesVolumeIdIndexRoute
  dashboardBackupsBackupIdSnapshotIdRestoreRoute: typeof dashboardBackupsBackupIdSnapshotIdRestoreRoute
  dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute: typeof dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute
  dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute: typeof dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardBackupsCreateRoute: dashboardBackupsCreateRoute,
  dashboardNotificationsCreateRoute: dashboardNotificationsCreateRoute,
  dashboardRepositoriesCreateRoute: dashboardRepositoriesCreateRoute,
  dashboardVolumesCreateRoute: dashboardVolumesCreateRoute,
  dashboardActivityIndexRoute: dashboardActivityIndexRoute,
  dashboardAdminIndexRoute: dashboardAdminIndexRoute,
  dashboardBackupsIndexRoute: dashboardBackupsIndexRoute,
  dashboardNotificationsIndexRoute: dashboardNotificationsIndexRoute,
  dashboardRepositoriesIndexRoute: dashboardRepositoriesIndexRoute,
  dashboardSettingsIndexRoute: dashboardSettingsIndexRoute,
  dashboardVolumesIndexRoute: dashboardVolumesIndexRoute,
  dashboardBackupsBackupIdEditRoute: dashboardBackupsBackupIdEditRoute,
  dashboardNotificationsNotificationIdEditRoute:
    dashboardNotificationsNotificationIdEditRoute,
  dashboardRepositoriesRepositoryIdEditRoute:
    dashboardRepositoriesRepositoryIdEditRoute,
  dashboardSettingsSsoNewRoute: dashboardSettingsSsoNewRoute,
  dashboardVolumesVolumeIdEditRoute: dashboardVolumesVolumeIdEditRoute,
  dashboardBackupsBackupIdIndexRoute: dashboardBackupsBackupIdIndexRoute,
  dashboardNotificationsNotificationIdIndexRoute:
    dashboardNotificationsNotificationIdIndexRoute,
  dashboardRepositoriesRepositoryIdIndexRoute:
    dashboardRepositoriesRepositoryIdIndexRoute,
  dashboardVolumesVolumeIdIndexRoute: dashboardVolumesVolumeIdIndexRoute,
  dashboardBackupsBackupIdSnapshotIdRestoreRoute:
    dashboardBackupsBackupIdSnapshotIdRestoreRoute,
  dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute:
    dashboardRepositoriesRepositoryIdSnapshotIdRestoreRoute,
  dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute:
    dashboardRepositoriesRepositoryIdSnapshotIdIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  DesktopTrayRoute: DesktopTrayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
