name: Integration Tests
permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  integration:
    name: Integration
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install dependencies
        uses: "./.github/actions/install-dependencies"

      - name: Run integration tests
        env:
          SKIP_VOLUME_MOUNT_INTEGRATION_TESTS: "true"
        run: bun run test:integration

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure()
        with:
          name: integration-artifacts
          path: |
            app/test/integration/artifacts/compose.log
            app/test/integration/artifacts/docker-output.log
            app/test/integration/artifacts/runs/**
          retention-days: 5
